/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Returns a fresh access + refresh token pair and starts a new token family (session). Wrong credentials → 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated — token pair issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-register and log in
         * @description Creates an account (assigned **no** role) and logs it straight in, returning a token pair. Duplicate email or a missing field → 422.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account created and logged in — token pair issued. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponseEnvelope"];
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a fresh pair
         * @description Refresh tokens are single-use and **rotate**: this revokes the presented
         *     token and issues a new pair in the same family. Presenting an already-spent
         *     token is treated as a leak and revokes the whole family. Unknown / expired /
         *     revoked token → 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description A fresh token pair in the same family. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out this device
         * @description Revokes the presented token's **family** (one session/device). Best-effort and idempotent — an unknown token still returns 204.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description Session revoked (or already gone). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out all devices
         * @description Revokes **every** family of the token's owner. Idempotent → 204.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description All the owner's sessions revoked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Public, unauthenticated, unthrottled. Runs `SELECT 1` against the database.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthEnvelope"];
                    };
                };
                /** @description Database unreachable (`checks.database` is `"error"`). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated user's profile
         * @description Available to every authenticated user (never gated). Returns the profile, the user's albums and their role names.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Me"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's roles and effective permissions
         * @description For a client to build its UI from — role names plus the union of their role-granted permission names. Never gated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Roles and permissions of the caller. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["MePermissions"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Requires `user.index.any` (moderator+). Supports `?expand=albums`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1). Out-of-range pages return an empty set. */
                    page?: components["parameters"]["page"];
                    /** @description Items per page, 1–100 (default 20). */
                    per_page?: components["parameters"]["perPage"];
                    /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `first_name`, `last_name`, `email`, `created_at`, `updated_at`. */
                    sort?: string;
                    /** @description Partial match. */
                    first_name?: string;
                    /** @description Partial match. */
                    last_name?: string;
                    /** @description Partial match. */
                    email?: string;
                    /** @description Comma-separated related resources to embed (e.g. `albums` on users, `photos` on albums). */
                    expand?: components["parameters"]["expand"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of users. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items?: components["schemas"]["User"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /**
         * Create a user
         * @description Requires `user.create` (admin+). The account is created with **no** role. Password is hashed server-side.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreateRequest"];
                };
            };
            responses: {
                /** @description User created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get a user
         * @description Requires `user.view.any` (moderator+) — ownership does **not** grant it. Always includes the user's albums.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user with albums. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["UserWithAlbums"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a user (partial)
         * @description Requires ownership (own profile) or `user.update.any` (admin+). All fields optional. An admin cannot take over a role-manager's account (409).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete a user
         * @description Requires `user.delete.any` (admin+). Blocked by the last-role-manager invariant (409).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Update a user (partial, alias of PUT) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * List a user's roles
         * @description Requires `role.assign` (admin+).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user's roles. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Role"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Replace a user's role set
         * @description Requires `role.assign` (admin+). Full replacement — an empty array revokes
         *     every role (back to a base user). Anti-escalation and the last-role-manager
         *     invariant are enforced (403 / 409). Unknown role name → 422.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleAssignRequest"];
                };
            };
            responses: {
                /** @description The user's new role set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Role"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own albums
         * @description Available to every authenticated user. Soft-deleted albums are excluded.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1). Out-of-range pages return an empty set. */
                    page?: components["parameters"]["page"];
                    /** @description Items per page, 1–100 (default 20). */
                    per_page?: components["parameters"]["perPage"];
                    /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `user_id`, `title`, `created_at`, `updated_at`. */
                    sort?: components["parameters"]["albumSort"];
                    /** @description Partial match. */
                    title?: string;
                    /** @description Comma-separated related resources to embed (e.g. `albums` on users, `photos` on albums). */
                    expand?: components["parameters"]["expand"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of the caller's albums. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all albums (review view)
         * @description Requires `album.index.any` (moderator+). Soft-deleted albums are hidden unless requested via `?is_deleted=1` (the review queue). Supports `?expand=photos`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1). Out-of-range pages return an empty set. */
                    page?: components["parameters"]["page"];
                    /** @description Items per page, 1–100 (default 20). */
                    per_page?: components["parameters"]["perPage"];
                    /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `user_id`, `title`, `created_at`, `updated_at`. */
                    sort?: components["parameters"]["albumSort"];
                    /** @description Partial match. */
                    title?: string;
                    /** @description Exact match on owner. */
                    user_id?: number;
                    /** @description Exact match. Omit to see only live albums; `1` surfaces the soft-deleted review queue. */
                    is_deleted?: boolean;
                    /** @description Comma-separated related resources to embed (e.g. `albums` on users, `photos` on albums). */
                    expand?: components["parameters"]["expand"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of albums. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumListEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /**
         * Create an album
         * @description A base ability of every authenticated user. The owner is forced to the caller — `user_id` cannot be set from the body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlbumCreateRequest"];
                };
            };
            responses: {
                /** @description Album created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Album"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get an album with its photos and owner
         * @description Requires ownership or `album.view.any` (moderator+). Returns a richer shape including the owner's name and the album's photos.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The album with photos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AlbumView"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update an album (partial)
         * @description Requires ownership or `album.update.any` (moderator+). Only the title is editable.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlbumUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated album. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Album"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete an album (permanent or soft)
         * @description One route, outcome decided by permission:
         *     - **Permanent** for the owner or a holder of `album.delete.any` (admin+) — the album, its photos and their files are removed.
         *     - **Soft** (flag + optional reason, idempotent) for holders of `album.soft-delete.any` (moderator) only. The optional JSON body carries the review reason.
         *
         *     Permanent wins if a role has both.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            /** @description Only consulted for a soft delete. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AlbumSoftDeleteRequest"];
                };
            };
            responses: {
                /** @description Album deleted (permanently or soft-flagged). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        options?: never;
        head?: never;
        /** Update an album (partial, alias of PUT) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlbumUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated album. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Album"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/albums/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a soft-deleted album
         * @description Requires `album.restore` (admin+). Lifts the pseudo-deletion after review.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The restored album. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Album"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{albumId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                albumId: number;
            };
            cookie?: never;
        };
        /**
         * List an album's photos
         * @description Requires ownership of the album or `photo.view.any` (moderator+). A missing album → 404.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1). Out-of-range pages return an empty set. */
                    page?: components["parameters"]["page"];
                    /** @description Items per page, 1–100 (default 20). */
                    per_page?: components["parameters"]["perPage"];
                    /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `title`, `created_at`. */
                    sort?: string;
                    /** @description Partial match. */
                    title?: string;
                };
                header?: never;
                path: {
                    albumId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of photos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items?: components["schemas"]["Photo"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /**
         * Upload a photo into an album
         * @description Requires ownership of the album or `photo.create.any` (moderator+).
         *     The **only** `multipart/form-data` endpoint. Allowed extensions:
         *     `jpg, jpeg, png, webp, gif, avif`. Every upload is converted to WebP
         *     quality 80, scaled to fit 500×500 preserving aspect ratio (never
         *     upscaled). A non-image passing the extension check → 422.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        title: string;
                        /**
                         * Format: binary
                         * @description The image file (jpg, jpeg, png, webp, gif, avif).
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Photo uploaded and stored as WebP. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Photo"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get a photo
         * @description Requires ownership (via the album) or `photo.view.any` (moderator+).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The photo. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Photo"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a photo (title only)
         * @description Requires ownership or `photo.update.any` (moderator+). The album and the stored file are immutable — only the title can change.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated photo. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Photo"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete a photo
         * @description Requires ownership or `photo.delete.any` (moderator+). Removes the record and, for uploaded photos, the physical file.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Photo deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a photo (title only, alias of PUT) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated photo. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Photo"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles
         * @description Requires `role.index` (admin+). Returns name + description (no permission sets).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1). Out-of-range pages return an empty set. */
                    page?: components["parameters"]["page"];
                    /** @description Items per page, 1–100 (default 20). */
                    per_page?: components["parameters"]["perPage"];
                    /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `name`. */
                    sort?: string;
                    /** @description Partial match. */
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of roles. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items?: components["schemas"]["Role"][];
                                pagination?: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /**
         * Compose a custom role
         * @description Requires `role.manage` (super-admin). Built from catalog permissions; an unknown permission name → 422, a duplicate role name → 422.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleCreateRequest"];
                };
            };
            responses: {
                /** @description Role created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        /**
         * Get a role with its permissions
         * @description Requires `role.view` (super-admin). Includes the role's permission set.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The role with permissions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RoleWithPermissions"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Re-compose a role (partial)
         * @description Requires `role.manage` (super-admin). A system role can be re-composed but
         *     not renamed (422). Blocked by the last-role-manager invariant (409).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated role. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete a custom role
         * @description Requires `role.manage` (super-admin). A system role cannot be deleted (409). Blocked by the last-role-manager invariant (409).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Re-compose a role (partial, alias of PUT) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["idPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated role. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the permission catalog
         * @description Requires `permission.index` (super-admin). Read-only — permissions are managed by migrations.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The whole catalog, ordered by name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Permission"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The unified success envelope. Concrete responses refine `data`. */
        SuccessEnvelope: {
            /** @example true */
            success: boolean;
            data: unknown;
            /** @example 200 */
            code: number;
        };
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /** @example 404 */
            code: number;
            data: {
                /** @example An error occurred during execution */
                message?: string;
                /** @description Details; only populated for validation errors, or with a stack trace when `YII_DEBUG`. */
                error?: {
                    [key: string]: unknown;
                };
            };
        };
        ValidationErrorEnvelope: {
            /** @example false */
            success: boolean;
            /** @example 422 */
            code: number;
            data: {
                /** @example An error occurred during execution */
                message?: string;
                /**
                 * @description Field name → list of validation messages.
                 * @example {
                 *       "email": [
                 *         "Email cannot be blank."
                 *       ]
                 *     }
                 */
                error?: {
                    [key: string]: string[];
                };
            };
        };
        Pagination: {
            /** @example 45 */
            total?: number;
            /** @example 20 */
            per_page?: number;
            /** @example 1 */
            current_page?: number;
            /** @example 3 */
            last_page?: number;
            /** @example 1 */
            from?: number;
            /** @example 20 */
            to?: number;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        RegisterRequest: {
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        RefreshTokenRequest: {
            /** @example 3f7c1e9a8b2d... */
            refresh_token: string;
        };
        TokenResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token?: string;
            /** @example 3f7c1e9a8b2d... */
            refresh_token?: string;
            /** @example Bearer */
            token_type?: string;
            /**
             * @description Access-token lifetime in seconds.
             * @example 3600
             */
            expires_in?: number;
        };
        TokenResponseEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: components["schemas"]["TokenResponse"];
        };
        HealthEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: {
                /**
                 * @example ok
                 * @enum {string}
                 */
                status?: "ok" | "error";
                checks?: {
                    /**
                     * @example ok
                     * @enum {string}
                     */
                    database?: "ok" | "error";
                };
            };
        };
        User: {
            /** @example 12 */
            id?: number;
            /** @example John */
            first_name?: string;
            /** @example Doe */
            last_name?: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email?: string;
        };
        UserWithAlbums: components["schemas"]["User"] & {
            albums?: components["schemas"]["Album"][];
        };
        Me: components["schemas"]["UserWithAlbums"] & {
            roles?: string[];
        };
        MePermissions: {
            roles?: string[];
            permissions?: string[];
        };
        UserCreateRequest: {
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        /** @description All fields optional — partial update. */
        UserUpdateRequest: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string;
            password?: string;
        };
        /** @description Album list/summary shape. */
        Album: {
            /** @example 5 */
            id?: number;
            /** @example Vacation 2025 */
            title?: string;
            /** @example false */
            is_deleted?: boolean;
            /** @example null */
            delete_reason?: string | null;
        };
        /** @description Richer single-album shape — includes the owner's name and the album's photos. */
        AlbumView: {
            /** @example 5 */
            id?: number;
            /** @example Vacation 2025 */
            title?: string;
            /**
             * @description Owner's first name.
             * @example John
             */
            first_name?: string;
            /**
             * @description Owner's last name.
             * @example Doe
             */
            last_name?: string;
            /** @example false */
            is_deleted?: boolean;
            /** @example null */
            delete_reason?: string | null;
            photos?: components["schemas"]["Photo"][];
        };
        AlbumListEnvelope: components["schemas"]["SuccessEnvelope"] & {
            data?: {
                items?: components["schemas"]["Album"][];
                pagination?: components["schemas"]["Pagination"];
            };
        };
        AlbumCreateRequest: {
            /** @example Vacation 2025 */
            title: string;
        };
        /** @description All fields optional — partial update. */
        AlbumUpdateRequest: {
            title?: string;
        };
        /** @description Optional body for a soft delete. */
        AlbumSoftDeleteRequest: {
            /** @example Reported for review */
            reason?: string;
        };
        Photo: {
            /** @example 41 */
            id?: number;
            /** @example Beach sunset */
            title?: string;
            /** @example http://localhost:8084/uploads/albums/5/8f3ac91b.webp */
            url?: string | null;
        };
        /** @description Only the title may change. */
        PhotoUpdateRequest: {
            title?: string;
        };
        Role: {
            /** @example 2 */
            id?: number;
            /** @example moderator */
            name?: string;
            /** @example Can moderate albums and photos */
            description?: string;
            /**
             * @description Seeded roles (moderator/admin/super_admin) — cannot be renamed or deleted.
             * @example true
             */
            is_system?: boolean;
        };
        RoleWithPermissions: components["schemas"]["Role"] & {
            permissions?: components["schemas"]["Permission"][];
        };
        Permission: {
            /** @example album.update.any */
            name?: string;
            /** @example Update any album */
            description?: string;
        };
        RoleCreateRequest: {
            /** @example editor */
            name: string;
            /** @example Can edit any album */
            description?: string;
            /** @description Catalog permission names to grant. */
            permissions?: string[];
        };
        /** @description All fields optional — partial update. Sending `permissions` replaces the set. */
        RoleUpdateRequest: {
            name?: string;
            description?: string;
            permissions?: string[];
        };
        RoleAssignRequest: {
            /** @description The full replacement set of role names. An empty array revokes all roles. */
            roles: string[];
        };
    };
    responses: {
        /** @description Missing / invalid access token, or bad credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but lacking the required permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found (or not visible to the caller). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The operation would violate a safety invariant (e.g. the last role manager). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request body or query validation failed. `data.error` maps each field to its messages. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorEnvelope"];
            };
        };
        /** @description Rate limit exceeded (see the `Retry-After` header). */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        idPath: number;
        /** @description Page number (default 1). Out-of-range pages return an empty set. */
        page: number;
        /** @description Items per page, 1–100 (default 20). */
        perPage: number;
        /** @description Comma-separated related resources to embed (e.g. `albums` on users, `photos` on albums). */
        expand: string;
        /** @description Comma-separated, `-` prefix = descending. Allowed: `id`, `user_id`, `title`, `created_at`, `updated_at`. */
        albumSort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
